# Generated by Django 5.2.1 on 2025-06-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prato',
            name='tempo_preparo',
        ),
    ]
