# Generated by Django 5.2.1 on 2025-06-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0002_remove_prato_tempo_preparo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='tempo_preparo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
