# Generated by Django 5.2.1 on 2025-06-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0003_prato_tempo_preparo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prato',
            old_name='rendinmento',
            new_name='rendimento',
        ),
    ]
