# Generated by Django 5.2.1 on 2025-07-05 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0004_rename_rendinmento_prato_rendimento'),
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='Funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario'),
            preserve_default=False,
        ),
    ]
