# Generated by Django 5.2.1 on 2025-07-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0006_prato_foto_prato_prato_publicado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prato',
            old_name='Funcionario',
            new_name='funcionario',
        ),
    ]
