# Generated by Django 5.2.1 on 2025-07-26 14:36

import churras.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0007_rename_funcionario_prato_funcionario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='foto_prato',
            field=models.ImageField(blank=True, upload_to=churras.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='prato',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
